# Generated by Django 3.0.5 on 2023-12-06 05:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('brewery_type', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=255)),
                ('phone', models.CharField(default='', editable=False, max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Brewery')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ratings.Brewery')),
            ],
        ),
    ]
