# Generated by Django 3.0.5 on 2023-12-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
