# Generated by Django 3.0.5 on 2023-12-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20231206_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='phone',
        ),
        migrations.AddField(
            model_name='rating',
            name='brewery_phone',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ratings.Brewery', to_field='phone'),
        ),
    ]
