# Generated by Django 4.2.8 on 2023-12-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
